title: Tilia Translations di Angela Brisotto
logo: /assets/img/Pagina corsi di aggiornamento.png
description: Minimal is a theme for GitHub Pages.
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
