title: Tilia Translations di Angela Brisotto
logo: /assets/img/Corsi di aggiornamento_pagina.jpg
description: Corsi di aggiornamento
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
